name: release
on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: |
        npm ci
        npm run toc
        git add README.md
      env:
        CI: true
    - run: npx semantic-release
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
